# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Kithongo Mutua
description: "Data Alchemist: Crafting Insights from Chaos - A Portfolio of Analytical Wizardry"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Nairobi, Kenya"
resume_url: /img/Resume_Daniel_Kithongo_Mutua.pdf
avatar_image: /img/Picture Cropped.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/daniel-kithongo-mutua/"
github: "https://github.com/kitmutua/kitmutua.github.io"
paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


